STRINGS = {
    "ru": {
        "welcome": "Добро пожаловать! Пожалуйста, выберите язык.\nWelcome! Please choose your language.",
        "language_selected": "Язык установлен: Русский 🇷🇺",
        "menu_products": "📦 Товары",
        "menu_stock": "📊 Наличие товаров",
        "menu_rules": "📜 Правила",
        "menu_help": "🆘 Помощь",
        "menu_projects": "🚀 Наши проекты",
        "menu_profile": "👤 Профиль",
        "back": "⬅️ Назад",
        "products_title": "Выберите категорию или товар:",
        "stock_title": "📦 Наличие товаров:",
        "rules_text": "📜 Правила нашего магазина:\n1. Не передавайте купленные товары третьим лицам.\n2. В случае проблем пишите в поддержку.\n3. Возврат средств только в случае невалида.",
        "help_text": "🆘 Помощь:\nЕсли у вас возникли вопросы, обратитесь к администратору @admin",
        "projects_text": "🚀 Наши другие проекты:\n- Бот 1\n- Канал 2",
        "buy_button": "💳 Купить за ${price}",
        "out_of_stock": "❌ Товар закончился",
        "invoice_created": "✅ Счет создан!\n\nОплатите по ссылке ниже:",
        "pay_link": "🔗 Оплатить",
        # Admin Panel
        "admin_panel": "🛠 Панель администратора",
        "admin_menu": "⚙️ Меню администратора:\n\nВыберите действие:",
        "add_product": "➕ Добавить товар",
        "edit_product": "✏️ Редактировать товар",
        "delete_product": "🗑️ Удалить товар",
        "manage_stock": "📦 Управление наличием",
        "manage_files": "📤 Управление файлами",
        "manage_codes": "🔑 Управление кодами",
        "recent_orders": "📊 Последние заказы",
        # Add Product Flow
        "choose_product_type": "Выберите тип товара:\n\n📎 link - URL ссылка\n📁 file - Telegram файл\n🔐 code - Код/Лицензия",
        "enter_title_en": "Введите название товара (английский):",
        "enter_title_ru": "Введите название товара (русский):",
        "enter_desc_en": "Введите описание (английский):",
        "enter_desc_ru": "Введите описание (русский):",
        "enter_price": "Введите цену в USD (например, 5.99):",
        "enter_stock": "Введите начальное количество на складе:",
        "enter_link": "Отправьте URL ссылку:",
        "send_file": "Отправьте файл:",
        "send_codes": "Отправьте коды (один на строку):",
        "product_created": "✅ Товар успешно создан!\nID: {product_id}",
        "codes_added": "✅ Добавлено {count} кодов",
        "operation_canceled": "❌ Операция отменена",
        "invalid_input": "❌ Неверный ввод, попробуйте снова",
        "not_authorized": "🚫 Вы не авторизованы для использования этой команды",
        # Delivery
        "code_delivered": "🔑 Ваш код:\n`{code}`",
        "link_delivered": "🔗 Ваша ссылка:\n{link}",
        "file_delivered": "📁 Ваш файл:",
        "no_codes_available": "⚠️ Коды отсутствуют. Свяжитесь с поддержкой.",
        "product_delivered": "🎁 Спасибо за покупку!\nВаш товар:\n{content}",
        "check_payment": "🔄 Проверить оплату",
        "choose_category": "🗂 <b>Категории:</b>\n\nВыберите категорию ниже:",
        "choose_product": "🛒 <b>В наличии:</b>\n\n--- 📦 Товары ---",
        "out_of_stock_detailed": "❌ Товар <b>{name}</b> закончился\n\nВы можете добавить товар в избранное, тогда получите уведомление при его пополнении.",
        "btn_add_favorite": "⭐ Добавить в избранное для отслеживания",
        "btn_back": "⬅️ Назад",
        "btn_back_categories": "⬅️ Назад ко всем категориям",
        "favorite_added_success": "✅ Добавлено в избранное. Мы уведомим вас при пополнении.",
        "restock_notification": "✅ Товар снова в наличии:\n<b>{name}</b>\nЦена: {price}$ | Остаток: {stock} шт.",
        "buy_from_restock": "🛒 Купить",
        "profile_text": "👤 <b>Ваш профиль:</b>\n\n────────────────────\n\n🪣 Мой ID: <code>{user_id}</code>\n\n💰 Мой баланс: {balance} $\n\n🛒 Количество покупок: {purchases_count}\n\n⏱ Регистрация: {registered_at}\n\n────────────────────\nℹ️ <i>Usernames update automatically when users interact.</i>",
        # Profile buttons
        "btn_topup": "💰 Пополнить баланс",
        "btn_my_purchases": "🛒 Мои покупки",
        "btn_my_topups": "💳 Мои пополнения",
        "btn_activate_coupon": "🎁 Активировать купон",
        # Topup flow
        "topup_enter_amount": "💰 Введите сумму пополнения (например 10):\n\n<i>Минимум: $1</i>",
        "topup_invalid_amount": "❌ Неверная сумма. Введите число от 1 и выше.",
        "topup_invoice_created": "✅ Ссылка для оплаты создана.\nСумма: <b>${amount}</b>\n\nНажмите «Оплатить».",
        "topup_pay_btn": "💳 Оплатить ${amount}",
        "topup_check_btn": "🔄 Проверить оплату",
        "topup_success": "✅ Оплата подтверждена. Баланс пополнен на ${amount}.\nНовый баланс: <b>${new_balance}</b>",
        "topup_not_paid": "⏳ Оплата еще не получена. Попробуйте позже.",
        "topup_already_paid": "✅ Эта оплата уже была обработана.",
        "topup_error": "❌ Ошибка создания счета. Попробуйте позже.",
        "topup_cancel": "❌ Отмена",
        "topup_cancelled": "❌ Пополнение отменено.",
        # My purchases / topups
        "no_purchases": "🛒 У вас пока нет покупок.",
        "no_topups": "💳 У вас пока нет пополнений.",
        # Balance Purchases
        "buy_full_balance": "✅ Покупка успешна. Списано с баланса: ${price}.",
        "buy_partial_balance": "🧾 <b>Счет #{invoice_id}</b>\n📦 Товар: {title}\n💰 Используем с баланса: <b>${used_balance}</b>\n➕ Доплатите только: <b>${need_crypto}</b> через CryptoBot.\n\n⏳ Товар зарезервирован на 15 минут.\n✅ Оплатите по ссылке ниже:",
        "buy_no_balance": "🧾 <b>Счет #{invoice_id}</b>\n📦 Товар: {title}\n💰 Для покупки оплатите <b>${price}</b> через CryptoBot.\n\n⏳ Товар зарезервирован на 15 минут.\n✅ Оплатите по ссылке ниже:",
    },
    "en": {
        "welcome": "Welcome! Please choose your language.",
        "language_selected": "Language set: English 🇬🇧",
        "menu_products": "📦 Products",
        "menu_stock": "📊 Stock",
        "menu_rules": "📜 Rules",
        "menu_help": "🆘 Help",
        "menu_projects": "🚀 Our projects",
        "menu_profile": "👤 Profile",
        "back": "⬅️ Back",
        "products_title": "Choose a product:",
        "stock_title": "📦 Product Stock:",
        "rules_text": "📜 Shop Rules:\n1. Do not share purchased items.\n2. Contact support for issues.\n3. Refunds only for invalid goods.",
        "help_text": "🆘 Help:\nContact admin @admin for assistance.",
        "projects_text": "🚀 Our other projects:\n- Bot 1\n- Channel 2",
        "buy_button": "💳 Buy for ${price}",
        "out_of_stock": "❌ Out of stock",
        "invoice_created": "✅ Invoice created!\n\nPlease pay using the link below:",
        "pay_link": "🔗 Pay",
        # Admin Panel
        "admin_panel": "🛠 Admin Panel",
        "admin_menu": "⚙️ Admin Menu:\n\nChoose an action:",
        "add_product": "➕ Add Product",
        "edit_product": "✏️ Edit Product",
        "delete_product": "🗑️ Delete Product",
        "manage_stock": "📦 Manage Stock",
        "manage_files": "📤 Manage Files",
        "manage_codes": "🔑 Manage Codes",
        "recent_orders": "📊 Recent Orders",
        # Add Product Flow
        "choose_product_type": "Choose product type:\n\n📎 link - URL link\n📁 file - Telegram file\n🔐 code - Code/License",
        "enter_title_en": "Enter product title (English):",
        "enter_title_ru": "Enter product title (Russian):",
        "enter_desc_en": "Enter description (English):",
        "enter_desc_ru": "Enter description (Russian):",
        "enter_price": "Enter price in USD (e.g., 5.99):",
        "enter_stock": "Enter initial stock quantity:",
        "enter_link": "Send the URL link:",
        "send_file": "Send the file:",
        "send_codes": "Send codes (one per line):",
        "product_created": "✅ Product created successfully!\nID: {product_id}",
        "codes_added": "✅ Added {count} codes",
        "operation_canceled": "❌ Operation canceled",
        "invalid_input": "❌ Invalid input, try again",
        "not_authorized": "🚫 You are not authorized to use this command",
        # Delivery
        "code_delivered": "🔑 Your code:\n`{code}`",
        "link_delivered": "🔗 Your link:\n{link}",
        "file_delivered": "📁 Your file:",
        "no_codes_available": "⚠️ No codes available. Contact support.",
        "product_delivered": "🎁 Thank you for your purchase!\nHere is your item:\n{content}",
        "check_payment": "🔄 Check Payment",
        "choose_category": "🗂 <b>Categories:</b>\n\nChoose a category below:",
        "choose_product": "🛒 <b>In stock:</b>\n\n--- 📦 Products ---",
        "out_of_stock_detailed": "❌ Product <b>{name}</b> is out of stock\n\nYou can add it to favorites and you will be notified when it’s restocked.",
        "btn_add_favorite": "⭐ Add to favorites to track",
        "btn_back": "⬅️ Back",
        "btn_back_categories": "⬅️ Back to categories",
        "favorite_added_success": "✅ Added to favorites. We’ll notify you when it’s restocked.",
        "restock_notification": "✅ Back in stock:\n<b>{name}</b>\nPrice: {price}$ | Stock: {stock} pcs.",
        "buy_from_restock": "🛒 Buy",
        "profile_text": "👤 <b>Your profile:</b>\n\n────────────────────\n\n🪣 My ID: <code>{user_id}</code>\n\n💰 My balance: {balance} $\n\n🛒 Purchases: {purchases_count}\n\n⏱ Registration: {registered_at}\n\n────────────────────\nℹ️ <i>Usernames update automatically when users interact.</i>",
        # Profile buttons
        "btn_topup": "💰 Top up balance",
        "btn_my_purchases": "🛒 My purchases",
        "btn_my_topups": "💳 My top-ups",
        "btn_activate_coupon": "🎁 Activate coupon",
        # Topup flow
        "topup_enter_amount": "💰 Enter top-up amount (e.g., 10):\n\n<i>Minimum: $1</i>",
        "topup_invalid_amount": "❌ Invalid amount. Enter a number from 1 and above.",
        "topup_invoice_created": "✅ Payment link created.\nAmount: <b>${amount}</b>\n\nClick \"Pay\".",
        "topup_pay_btn": "💳 Pay ${amount}",
        "topup_check_btn": "🔄 Check payment",
        "topup_success": "✅ Payment confirmed. Balance increased by ${amount}.\nNew balance: <b>${new_balance}</b>",
        "topup_not_paid": "⏳ Payment not received yet. Try again later.",
        "topup_already_paid": "✅ This payment has already been processed.",
        "topup_error": "❌ Error creating invoice. Try again later.",
        "topup_cancel": "❌ Cancel",
        "topup_cancelled": "❌ Top-up cancelled.",
        # My purchases / topups
        "no_purchases": "🛒 You have no purchases yet.",
        "no_topups": "💳 You have no top-ups yet.",
        # Balance Purchases
        "buy_full_balance": "✅ Purchase successful. Deducted from balance: ${price}.",
        "buy_partial_balance": "🧾 <b>Invoice #{invoice_id}</b>\n📦 Product: {title}\n💰 Using from balance: <b>${used_balance}</b>\n➕ Please pay only: <b>${need_crypto}</b> via CryptoBot.\n\n⏳ Stock reserved for 15 minutes.\n✅ Please pay using the link below:",
        "buy_no_balance": "🧾 <b>Invoice #{invoice_id}</b>\n📦 Product: {title}\n💰 To purchase, please pay <b>${price}</b> via CryptoBot.\n\n⏳ Stock reserved for 15 minutes.\n✅ Please pay using the link below:",
    }
}

KEYBOARDS = {
    "ru": [
        ["📦 Товары", "📊 Наличие товаров"],
        ["📜 Правила", "🆘 Помощь"],
        ["🚀 Наши проекты", "👤 Профиль"]
    ],
    "en": [
        ["📦 Products", "📊 Stock"],
        ["📜 Rules", "🆘 Help"],
        ["🚀 Our projects", "👤 Profile"]
    ]
}
