STRINGS = {
    "ru": {
        "welcome": "Добро пожаловать! Пожалуйста, выберите язык.\nWelcome! Please choose your language.",
        "language_selected": "Язык установлен: Русский 🇷🇺",
        "menu_products": "📦 Товары",
        "menu_stock": "📊 Наличие товаров",
        "menu_rules": "📜 Правила",
        "menu_help": "🆘 Помощь",
        "menu_projects": "🚀 Наши проекты",
        "back": "⬅️ Назад",
        "products_title": "Выберите категорию или товар:",
        "stock_title": "📦 Наличие товаров:",
        "rules_text": "📜 Правила нашего магазина:\n1. Не передавайте купленные товары третьим лицам.\n2. В случае проблем пишите в поддержку.\n3. Возврат средств только в случае невалида.",
        "help_text": "🆘 Помощь:\nЕсли у вас возникли вопросы, обратитесь к администратору @admin",
        "projects_text": "🚀 Наши другие проекты:\n- Бот 1\n- Канал 2",
        "buy_button": "💳 Купить за ${price}",
        "out_of_stock": "❌ Товар закончился",
        "invoice_created": "✅ Счет создан!\n\nОплатите по ссылке ниже:",
        "pay_link": "🔗 Оплатить",
        # Admin Panel
        "admin_panel": "🛠 Панель администратора",
        "admin_menu": "⚙️ Меню администратора:\n\nВыберите действие:",
        "add_product": "➕ Добавить товар",
        "edit_product": "✏️ Редактировать товар",
        "delete_product": "🗑️ Удалить товар",
        "manage_stock": "📦 Управление наличием",
        "manage_files": "📤 Управление файлами",
        "manage_codes": "🔑 Управление кодами",
        "recent_orders": "📊 Последние заказы",
        # Add Product Flow
        "choose_product_type": "Выберите тип товара:\n\n📎 link - URL ссылка\n📁 file - Telegram файл\n🔐 code - Код/Лицензия",
        "enter_title_en": "Введите название товара (английский):",
        "enter_title_ru": "Введите название товара (русский):",
        "enter_desc_en": "Введите описание (английский):",
        "enter_desc_ru": "Введите описание (русский):",
        "enter_price": "Введите цену в USD (например, 5.99):",
        "enter_stock": "Введите начальное количество на складе:",
        "enter_link": "Отправьте URL ссылку:",
        "send_file": "Отправьте файл:",
        "send_codes": "Отправьте коды (один на строку):",
        "product_created": "✅ Товар успешно создан!\nID: {product_id}",
        "codes_added": "✅ Добавлено {count} кодов",
        "operation_canceled": "❌ Операция отменена",
        "invalid_input": "❌ Неверный ввод, попробуйте снова",
        "not_authorized": "🚫 Вы не авторизованы для использования этой команды",
        # Delivery
        "code_delivered": "🔑 Ваш код:\n`{code}`",
        "link_delivered": "🔗 Ваша ссылка:\n{link}",
        "file_delivered": "📁 Ваш файл:",
        "no_codes_available": "⚠️ Коды отсутствуют. Свяжитесь с поддержкой.",
        "product_delivered": "🎁 Спасибо за покупку!\nВаш товар:\n{content}",
        "check_payment": "🔄 Проверить оплату",
        "choose_product": "Выберите товар:",
    },
    "en": {
        "welcome": "Welcome! Please choose your language.",
        "language_selected": "Language set: English 🇬🇧",
        "menu_products": "📦 Products",
        "menu_stock": "📊 Stock",
        "menu_rules": "📜 Rules",
        "menu_help": "🆘 Help",
        "menu_projects": "🚀 Our projects",
        "back": "⬅️ Back",
        "products_title": "Choose a product:",
        "stock_title": "📦 Product Stock:",
        "rules_text": "📜 Shop Rules:\n1. Do not share purchased items.\n2. Contact support for issues.\n3. Refunds only for invalid goods.",
        "help_text": "🆘 Help:\nContact admin @admin for assistance.",
        "projects_text": "🚀 Our other projects:\n- Bot 1\n- Channel 2",
        "buy_button": "💳 Buy for ${price}",
        "out_of_stock": "❌ Out of stock",
        "invoice_created": "✅ Invoice created!\n\nPlease pay using the link below:",
        "pay_link": "🔗 Pay",
        "product_delivered": "🎁 Thank you for your purchase!\nHere is your item:\n{content}",
        "check_payment": "🔄 Check Payment",
        "choose_product": "Choose a product:",
    }
}

KEYBOARDS = {
    "ru": [
        ["📦 Товары", "📊 Наличие товаров"],
        ["📜 Правила", "🆘 Помощь"],
        ["🚀 Наши проекты"]
    ],
    "en": [
        ["📦 Products", "📊 Stock"],
        ["📜 Rules", "🆘 Help"],
        ["🚀 Our projects"]
    ]
}
